// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart';
import 'package:googleapis_auth/auth_io.dart'

    show ServiceAccountCredentials, TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOLPeAJY2yo8-9QuT275KFsCGHEWEqVjs',
    appId: '1:721964679059:android:2358912abcbf12ed8a7266',
    messagingSenderId: '721964679059',
    projectId: 'transport-app-36443',
    databaseURL: 'https://transport-app-36443-default-rtdb.firebaseio.com',
    storageBucket: 'transport-app-36443.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN58h5tthuZwC5FCxrxiGA4EL4_HpFw5E',
    appId: '1:721964679059:ios:d43b1fd1aa751aa88a7266',
    messagingSenderId: '721964679059',
    projectId: 'transport-app-36443',
    databaseURL: 'https://transport-app-36443-default-rtdb.firebaseio.com',
    storageBucket: 'transport-app-36443.appspot.com',
    androidClientId: '721964679059-ehdr7dfvurbauar2at3lg7cjgvs00p1h.apps.googleusercontent.com',
    iosClientId: '721964679059-jbkljunl7h61f1m4lvnqpj67hc2hp0dh.apps.googleusercontent.com',
    iosBundleId: 'com.example.usersApp',
  );
  


}

